#!/bin/bash
# Set up enviroment to make Objective-C project

# Remove main.m if exist
if [ -e main.m ]; then
	rm main.m
fi

# Make new main.m
touch main.m

# Write content to main.m
echo '#import <Foundation/Foundation.h>
' >> main.m
echo 'int main(int argc, const char * argv[]){' >> main.m 
echo '	NSAutoreleasePool * pool = [[NSAutoreleasePool alloc] init];
' >> main.m
echo '	[pool drain];' >> main.m
echo '	return 0;' >> main.m
echo '}' >> main.m

